import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const lato = Inter({
  subsets: ['latin', 'vietnamese'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: "Can you date with me?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
